-- Sample seed data for Hatchlands development

-- ============================================================================
-- SAMPLE REGIONS
-- ============================================================================

INSERT INTO regions (id, latitude, longitude, radius, biome, temperature, humidity, elevation, created_at) VALUES
('region-forest-001', 51.5074, -0.1278, 1000, 'temperate_forest', 15.5, 70.0, 100.0, 1640000000000),
('region-desert-001', 36.7783, -119.4179, 1000, 'desert', 35.0, 15.0, 500.0, 1640000000000),
('region-ocean-001', 19.4326, -155.2908, 1000, 'ocean', 25.0, 85.0, 0.0, 1640000000000),
('region-mountain-001', 45.8215, 6.8651, 1000, 'mountain', 2.0, 60.0, 2500.0, 1640000000000),
('region-swamp-001', 29.9511, -90.0715, 1000, 'swamp', 28.0, 95.0, 10.0, 1640000000000);

-- ============================================================================
-- SAMPLE PLAYERS
-- ============================================================================

INSERT INTO players (id, username, email, password_hash, created_at, last_active_at, latitude, longitude, currency) VALUES
('player-001', 'dragonmaster', 'dragon@example.com', '$2b$10$test', 1640000000000, 1708560000000, 51.5074, -0.1278, 5000),
('player-002', 'beastcollector', 'beast@example.com', '$2b$10$test', 1640100000000, 1708560000000, 36.7783, -119.4179, 3000),
('player-003', 'wildtrainer', 'wild@example.com', '$2b$10$test', 1640200000000, 1708560000000, 19.4326, -155.2908, 4500);

-- ============================================================================
-- SAMPLE CREATURES (will be properly generated in the app)
-- ============================================================================

-- Note: In production, creatures are generated by the deterministic engine
-- These are simplified examples for development/testing

INSERT INTO creatures (
  id, seed, primary_anchor, secondary_anchor, genome_signature, appearance_params,
  owner_id, status, lineage_history, birth_timestamp, xp, level,
  created_at, updated_at
) VALUES
(
  'creature-001', 12345, 'dragon', NULL,
  '{"primaryGenes": [1,2,3,4], "mutations": [], "generation": 0}'::jsonb,
  '{"parts": {"body": "scales", "head": "horned", "limbs": ["clawed"], "wings": ["bat"]}, "colorIndices": [0,1], "materials": ["scales"], "scale": 1.1, "procedural": {}}'::jsonb,
  'player-001', 'captured', '[]'::jsonb, 1640000000000, 250, 3,
  1640000000000, 1640000000000
),
(
  'creature-002', 67890, 'phoenix', NULL,
  '{"primaryGenes": [5,6,7,8], "mutations": [], "generation": 0}'::jsonb,
  '{"parts": {"body": "feathers", "head": "crested", "limbs": ["taloned"], "wings": ["feathered"]}, "colorIndices": [2,3], "materials": ["feathers"], "scale": 0.9, "procedural": {}}'::jsonb,
  'player-001', 'captured', '[]'::jsonb, 1641000000000, 180, 2,
  1641000000000, 1641000000000
),
(
  'creature-003', 11111, 'kraken', NULL,
  '{"primaryGenes": [9,10,11,12], "mutations": [], "generation": 0}'::jsonb,
  '{"parts": {"body": "tentacles", "head": "beaked", "limbs": ["tentacle"]}, "colorIndices": [4,5], "materials": ["wet"], "scale": 1.3, "procedural": {}}'::jsonb,
  'player-003', 'captured', '[]'::jsonb, 1642000000000, 500, 5,
  1642000000000, 1642000000000
);

-- ============================================================================
-- SAMPLE MARKET LISTINGS
-- ============================================================================

INSERT INTO trade_listings (
  id, creature_id, seller_id, price, currency, listed_at, expires_at, active, created_at
) VALUES
(
  'listing-001', 'creature-002', 'player-001', 1500, 'coins',
  1708000000000, 1708604800000, TRUE, 1708000000000
);

-- Update creature status for listed creature
UPDATE creatures SET status = 'listed' WHERE id = 'creature-002';

-- ============================================================================
-- NOTES
-- ============================================================================

-- Spawns, encounters, and breeding requests are generated dynamically
-- and are not typically pre-seeded as they are time-sensitive
